<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('countries')->delete();
        
        \DB::table('countries')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'AFGHANISTAN',
                'iso' => 'AF',
                'phonecode' => 93,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'ALBANIA',
                'iso' => 'AL',
                'phonecode' => 355,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'ALGERIA',
                'iso' => 'DZ',
                'phonecode' => 213,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'AMERICAN SAMOA',
                'iso' => 'AS',
                'phonecode' => 1684,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'ANDORRA',
                'iso' => 'AD',
                'phonecode' => 376,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'ANGOLA',
                'iso' => 'AO',
                'phonecode' => 244,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'ANGUILLA',
                'iso' => 'AI',
                'phonecode' => 1264,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'ANTARCTICA',
                'iso' => 'AQ',
                'phonecode' => 0,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'ANTIGUA AND BARBUDA',
                'iso' => 'AG',
                'phonecode' => 1268,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'ARGENTINA',
                'iso' => 'AR',
                'phonecode' => 54,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'ARMENIA',
                'iso' => 'AM',
                'phonecode' => 374,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'ARUBA',
                'iso' => 'AW',
                'phonecode' => 297,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'AUSTRALIA',
                'iso' => 'AU',
                'phonecode' => 61,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'AUSTRIA',
                'iso' => 'AT',
                'phonecode' => 43,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'AZERBAIJAN',
                'iso' => 'AZ',
                'phonecode' => 994,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'BAHAMAS',
                'iso' => 'BS',
                'phonecode' => 1242,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'BAHRAIN',
                'iso' => 'BH',
                'phonecode' => 973,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'BANGLADESH',
                'iso' => 'BD',
                'phonecode' => 880,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'BARBADOS',
                'iso' => 'BB',
                'phonecode' => 1246,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'BELARUS',
                'iso' => 'BY',
                'phonecode' => 375,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'BELGIUM',
                'iso' => 'BE',
                'phonecode' => 32,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'BELIZE',
                'iso' => 'BZ',
                'phonecode' => 501,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'BENIN',
                'iso' => 'BJ',
                'phonecode' => 229,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'BERMUDA',
                'iso' => 'BM',
                'phonecode' => 1441,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'BHUTAN',
                'iso' => 'BT',
                'phonecode' => 975,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'BOLIVIA',
                'iso' => 'BO',
                'phonecode' => 591,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'BOSNIA AND HERZEGOVINA',
                'iso' => 'BA',
                'phonecode' => 387,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'BOTSWANA',
                'iso' => 'BW',
                'phonecode' => 267,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'BOUVET ISLAND',
                'iso' => 'BV',
                'phonecode' => 0,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'BRAZIL',
                'iso' => 'BR',
                'phonecode' => 55,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'BRITISH INDIAN OCEAN TERRITORY',
                'iso' => 'IO',
                'phonecode' => 246,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'name' => 'BRUNEI DARUSSALAM',
                'iso' => 'BN',
                'phonecode' => 673,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'name' => 'BULGARIA',
                'iso' => 'BG',
                'phonecode' => 359,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'name' => 'BURKINA FASO',
                'iso' => 'BF',
                'phonecode' => 226,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'name' => 'BURUNDI',
                'iso' => 'BI',
                'phonecode' => 257,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'name' => 'CAMBODIA',
                'iso' => 'KH',
                'phonecode' => 855,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'name' => 'CAMEROON',
                'iso' => 'CM',
                'phonecode' => 237,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'name' => 'CANADA',
                'iso' => 'CA',
                'phonecode' => 1,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'name' => 'CAPE VERDE',
                'iso' => 'CV',
                'phonecode' => 238,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'name' => 'CAYMAN ISLANDS',
                'iso' => 'KY',
                'phonecode' => 1345,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'name' => 'CENTRAL AFRICAN REPUBLIC',
                'iso' => 'CF',
                'phonecode' => 236,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'name' => 'CHAD',
                'iso' => 'TD',
                'phonecode' => 235,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'name' => 'CHILE',
                'iso' => 'CL',
                'phonecode' => 56,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'name' => 'CHINA',
                'iso' => 'CN',
                'phonecode' => 86,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'name' => 'CHRISTMAS ISLAND',
                'iso' => 'CX',
                'phonecode' => 61,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
            'name' => 'COCOS (KEELING) ISLANDS',
                'iso' => 'CC',
                'phonecode' => 672,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'name' => 'COLOMBIA',
                'iso' => 'CO',
                'phonecode' => 57,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'name' => 'COMOROS',
                'iso' => 'KM',
                'phonecode' => 269,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'name' => 'CONGO',
                'iso' => 'CG',
                'phonecode' => 242,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'name' => 'CONGO, THE DEMOCRATIC REPUBLIC OF THE',
                'iso' => 'CD',
                'phonecode' => 242,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'name' => 'COOK ISLANDS',
                'iso' => 'CK',
                'phonecode' => 682,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'name' => 'COSTA RICA',
                'iso' => 'CR',
                'phonecode' => 506,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'name' => 'COTE D\'IVOIRE',
                'iso' => 'CI',
                'phonecode' => 225,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'name' => 'CROATIA',
                'iso' => 'HR',
                'phonecode' => 385,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'name' => 'CUBA',
                'iso' => 'CU',
                'phonecode' => 53,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'name' => 'CYPRUS',
                'iso' => 'CY',
                'phonecode' => 357,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'name' => 'CZECH REPUBLIC',
                'iso' => 'CZ',
                'phonecode' => 420,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'name' => 'DENMARK',
                'iso' => 'DK',
                'phonecode' => 45,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'name' => 'DJIBOUTI',
                'iso' => 'DJ',
                'phonecode' => 253,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'name' => 'DOMINICA',
                'iso' => 'DM',
                'phonecode' => 1767,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'name' => 'DOMINICAN REPUBLIC',
                'iso' => 'DO',
                'phonecode' => 1809,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'name' => 'ECUADOR',
                'iso' => 'EC',
                'phonecode' => 593,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'name' => 'EGYPT',
                'iso' => 'EG',
                'phonecode' => 20,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'name' => 'EL SALVADOR',
                'iso' => 'SV',
                'phonecode' => 503,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            64 => 
            array (
                'id' => 65,
                'name' => 'EQUATORIAL GUINEA',
                'iso' => 'GQ',
                'phonecode' => 240,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            65 => 
            array (
                'id' => 66,
                'name' => 'ERITREA',
                'iso' => 'ER',
                'phonecode' => 291,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            66 => 
            array (
                'id' => 67,
                'name' => 'ESTONIA',
                'iso' => 'EE',
                'phonecode' => 372,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            67 => 
            array (
                'id' => 68,
                'name' => 'ETHIOPIA',
                'iso' => 'ET',
                'phonecode' => 251,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            68 => 
            array (
                'id' => 69,
            'name' => 'FALKLAND ISLANDS (MALVINAS)',
                'iso' => 'FK',
                'phonecode' => 500,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            69 => 
            array (
                'id' => 70,
                'name' => 'FAROE ISLANDS',
                'iso' => 'FO',
                'phonecode' => 298,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            70 => 
            array (
                'id' => 71,
                'name' => 'FIJI',
                'iso' => 'FJ',
                'phonecode' => 679,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            71 => 
            array (
                'id' => 72,
                'name' => 'FINLAND',
                'iso' => 'FI',
                'phonecode' => 358,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            72 => 
            array (
                'id' => 73,
                'name' => 'FRANCE',
                'iso' => 'FR',
                'phonecode' => 33,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            73 => 
            array (
                'id' => 74,
                'name' => 'FRENCH GUIANA',
                'iso' => 'GF',
                'phonecode' => 594,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            74 => 
            array (
                'id' => 75,
                'name' => 'FRENCH POLYNESIA',
                'iso' => 'PF',
                'phonecode' => 689,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            75 => 
            array (
                'id' => 76,
                'name' => 'FRENCH SOUTHERN TERRITORIES',
                'iso' => 'TF',
                'phonecode' => 0,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            76 => 
            array (
                'id' => 77,
                'name' => 'GABON',
                'iso' => 'GA',
                'phonecode' => 241,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            77 => 
            array (
                'id' => 78,
                'name' => 'GAMBIA',
                'iso' => 'GM',
                'phonecode' => 220,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            78 => 
            array (
                'id' => 79,
                'name' => 'GEORGIA',
                'iso' => 'GE',
                'phonecode' => 995,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            79 => 
            array (
                'id' => 80,
                'name' => 'GERMANY',
                'iso' => 'DE',
                'phonecode' => 49,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            80 => 
            array (
                'id' => 81,
                'name' => 'GHANA',
                'iso' => 'GH',
                'phonecode' => 233,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            81 => 
            array (
                'id' => 82,
                'name' => 'GIBRALTAR',
                'iso' => 'GI',
                'phonecode' => 350,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            82 => 
            array (
                'id' => 83,
                'name' => 'GREECE',
                'iso' => 'GR',
                'phonecode' => 30,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            83 => 
            array (
                'id' => 84,
                'name' => 'GREENLAND',
                'iso' => 'GL',
                'phonecode' => 299,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            84 => 
            array (
                'id' => 85,
                'name' => 'GRENADA',
                'iso' => 'GD',
                'phonecode' => 1473,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            85 => 
            array (
                'id' => 86,
                'name' => 'GUADELOUPE',
                'iso' => 'GP',
                'phonecode' => 590,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            86 => 
            array (
                'id' => 87,
                'name' => 'GUAM',
                'iso' => 'GU',
                'phonecode' => 1671,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            87 => 
            array (
                'id' => 88,
                'name' => 'GUATEMALA',
                'iso' => 'GT',
                'phonecode' => 502,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            88 => 
            array (
                'id' => 89,
                'name' => 'GUINEA',
                'iso' => 'GN',
                'phonecode' => 224,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            89 => 
            array (
                'id' => 90,
                'name' => 'GUINEA-BISSAU',
                'iso' => 'GW',
                'phonecode' => 245,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            90 => 
            array (
                'id' => 91,
                'name' => 'GUYANA',
                'iso' => 'GY',
                'phonecode' => 592,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            91 => 
            array (
                'id' => 92,
                'name' => 'HAITI',
                'iso' => 'HT',
                'phonecode' => 509,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            92 => 
            array (
                'id' => 93,
                'name' => 'HEARD ISLAND AND MCDONALD ISLANDS',
                'iso' => 'HM',
                'phonecode' => 0,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            93 => 
            array (
                'id' => 94,
            'name' => 'HOLY SEE (VATICAN CITY STATE)',
                'iso' => 'VA',
                'phonecode' => 39,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            94 => 
            array (
                'id' => 95,
                'name' => 'HONDURAS',
                'iso' => 'HN',
                'phonecode' => 504,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            95 => 
            array (
                'id' => 96,
                'name' => 'HONG KONG',
                'iso' => 'HK',
                'phonecode' => 852,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            96 => 
            array (
                'id' => 97,
                'name' => 'HUNGARY',
                'iso' => 'HU',
                'phonecode' => 36,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            97 => 
            array (
                'id' => 98,
                'name' => 'ICELAND',
                'iso' => 'IS',
                'phonecode' => 354,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            98 => 
            array (
                'id' => 99,
                'name' => 'INDIA',
                'iso' => 'IN',
                'phonecode' => 91,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            99 => 
            array (
                'id' => 100,
                'name' => 'INDONESIA',
                'iso' => 'ID',
                'phonecode' => 62,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            100 => 
            array (
                'id' => 101,
                'name' => 'IRAN, ISLAMIC REPUBLIC OF',
                'iso' => 'IR',
                'phonecode' => 98,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            101 => 
            array (
                'id' => 102,
                'name' => 'IRAQ',
                'iso' => 'IQ',
                'phonecode' => 964,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            102 => 
            array (
                'id' => 103,
                'name' => 'IRELAND',
                'iso' => 'IE',
                'phonecode' => 353,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            103 => 
            array (
                'id' => 104,
                'name' => 'ISRAEL',
                'iso' => 'IL',
                'phonecode' => 972,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            104 => 
            array (
                'id' => 105,
                'name' => 'ITALY',
                'iso' => 'IT',
                'phonecode' => 39,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            105 => 
            array (
                'id' => 106,
                'name' => 'JAMAICA',
                'iso' => 'JM',
                'phonecode' => 1876,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            106 => 
            array (
                'id' => 107,
                'name' => 'JAPAN',
                'iso' => 'JP',
                'phonecode' => 81,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            107 => 
            array (
                'id' => 108,
                'name' => 'JORDAN',
                'iso' => 'JO',
                'phonecode' => 962,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            108 => 
            array (
                'id' => 109,
                'name' => 'KAZAKHSTAN',
                'iso' => 'KZ',
                'phonecode' => 7,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            109 => 
            array (
                'id' => 110,
                'name' => 'KENYA',
                'iso' => 'KE',
                'phonecode' => 254,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            110 => 
            array (
                'id' => 111,
                'name' => 'KIRIBATI',
                'iso' => 'KI',
                'phonecode' => 686,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            111 => 
            array (
                'id' => 112,
                'name' => 'KOREA, DEMOCRATIC PEOPLE\'S REPUBLIC OF',
                'iso' => 'KP',
                'phonecode' => 850,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            112 => 
            array (
                'id' => 113,
                'name' => 'KOREA, REPUBLIC OF',
                'iso' => 'KR',
                'phonecode' => 82,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            113 => 
            array (
                'id' => 114,
                'name' => 'KUWAIT',
                'iso' => 'KW',
                'phonecode' => 965,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            114 => 
            array (
                'id' => 115,
                'name' => 'KYRGYZSTAN',
                'iso' => 'KG',
                'phonecode' => 996,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            115 => 
            array (
                'id' => 116,
                'name' => 'LAO PEOPLE\'S DEMOCRATIC REPUBLIC',
                'iso' => 'LA',
                'phonecode' => 856,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            116 => 
            array (
                'id' => 117,
                'name' => 'LATVIA',
                'iso' => 'LV',
                'phonecode' => 371,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            117 => 
            array (
                'id' => 118,
                'name' => 'LEBANON',
                'iso' => 'LB',
                'phonecode' => 961,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            118 => 
            array (
                'id' => 119,
                'name' => 'LESOTHO',
                'iso' => 'LS',
                'phonecode' => 266,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            119 => 
            array (
                'id' => 120,
                'name' => 'LIBERIA',
                'iso' => 'LR',
                'phonecode' => 231,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            120 => 
            array (
                'id' => 121,
                'name' => 'LIBYAN ARAB JAMAHIRIYA',
                'iso' => 'LY',
                'phonecode' => 218,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            121 => 
            array (
                'id' => 122,
                'name' => 'LIECHTENSTEIN',
                'iso' => 'LI',
                'phonecode' => 423,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            122 => 
            array (
                'id' => 123,
                'name' => 'LITHUANIA',
                'iso' => 'LT',
                'phonecode' => 370,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            123 => 
            array (
                'id' => 124,
                'name' => 'LUXEMBOURG',
                'iso' => 'LU',
                'phonecode' => 352,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            124 => 
            array (
                'id' => 125,
                'name' => 'MACAO',
                'iso' => 'MO',
                'phonecode' => 853,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            125 => 
            array (
                'id' => 126,
                'name' => 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF',
                'iso' => 'MK',
                'phonecode' => 389,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            126 => 
            array (
                'id' => 127,
                'name' => 'MADAGASCAR',
                'iso' => 'MG',
                'phonecode' => 261,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            127 => 
            array (
                'id' => 128,
                'name' => 'MALAWI',
                'iso' => 'MW',
                'phonecode' => 265,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            128 => 
            array (
                'id' => 129,
                'name' => 'MALAYSIA',
                'iso' => 'MY',
                'phonecode' => 60,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            129 => 
            array (
                'id' => 130,
                'name' => 'MALDIVES',
                'iso' => 'MV',
                'phonecode' => 960,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            130 => 
            array (
                'id' => 131,
                'name' => 'MALI',
                'iso' => 'ML',
                'phonecode' => 223,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            131 => 
            array (
                'id' => 132,
                'name' => 'MALTA',
                'iso' => 'MT',
                'phonecode' => 356,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            132 => 
            array (
                'id' => 133,
                'name' => 'MARSHALL ISLANDS',
                'iso' => 'MH',
                'phonecode' => 692,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            133 => 
            array (
                'id' => 134,
                'name' => 'MARTINIQUE',
                'iso' => 'MQ',
                'phonecode' => 596,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            134 => 
            array (
                'id' => 135,
                'name' => 'MAURITANIA',
                'iso' => 'MR',
                'phonecode' => 222,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            135 => 
            array (
                'id' => 136,
                'name' => 'MAURITIUS',
                'iso' => 'MU',
                'phonecode' => 230,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            136 => 
            array (
                'id' => 137,
                'name' => 'MAYOTTE',
                'iso' => 'YT',
                'phonecode' => 269,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            137 => 
            array (
                'id' => 138,
                'name' => 'MEXICO',
                'iso' => 'MX',
                'phonecode' => 52,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            138 => 
            array (
                'id' => 139,
                'name' => 'MICRONESIA, FEDERATED STATES OF',
                'iso' => 'FM',
                'phonecode' => 691,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            139 => 
            array (
                'id' => 140,
                'name' => 'MOLDOVA, REPUBLIC OF',
                'iso' => 'MD',
                'phonecode' => 373,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            140 => 
            array (
                'id' => 141,
                'name' => 'MONACO',
                'iso' => 'MC',
                'phonecode' => 377,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            141 => 
            array (
                'id' => 142,
                'name' => 'MONGOLIA',
                'iso' => 'MN',
                'phonecode' => 976,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            142 => 
            array (
                'id' => 143,
                'name' => 'MONTSERRAT',
                'iso' => 'MS',
                'phonecode' => 1664,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            143 => 
            array (
                'id' => 144,
                'name' => 'MOROCCO',
                'iso' => 'MA',
                'phonecode' => 212,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            144 => 
            array (
                'id' => 145,
                'name' => 'MOZAMBIQUE',
                'iso' => 'MZ',
                'phonecode' => 258,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            145 => 
            array (
                'id' => 146,
                'name' => 'MYANMAR',
                'iso' => 'MM',
                'phonecode' => 95,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            146 => 
            array (
                'id' => 147,
                'name' => 'NAMIBIA',
                'iso' => 'NA',
                'phonecode' => 264,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            147 => 
            array (
                'id' => 148,
                'name' => 'NAURU',
                'iso' => 'NR',
                'phonecode' => 674,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            148 => 
            array (
                'id' => 149,
                'name' => 'NEPAL',
                'iso' => 'NP',
                'phonecode' => 977,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            149 => 
            array (
                'id' => 150,
                'name' => 'NETHERLANDS',
                'iso' => 'NL',
                'phonecode' => 31,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            150 => 
            array (
                'id' => 151,
                'name' => 'NETHERLANDS ANTILLES',
                'iso' => 'AN',
                'phonecode' => 599,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            151 => 
            array (
                'id' => 152,
                'name' => 'NEW CALEDONIA',
                'iso' => 'NC',
                'phonecode' => 687,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            152 => 
            array (
                'id' => 153,
                'name' => 'NEW ZEALAND',
                'iso' => 'NZ',
                'phonecode' => 64,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            153 => 
            array (
                'id' => 154,
                'name' => 'NICARAGUA',
                'iso' => 'NI',
                'phonecode' => 505,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            154 => 
            array (
                'id' => 155,
                'name' => 'NIGER',
                'iso' => 'NE',
                'phonecode' => 227,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            155 => 
            array (
                'id' => 156,
                'name' => 'NIGERIA',
                'iso' => 'NG',
                'phonecode' => 234,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            156 => 
            array (
                'id' => 157,
                'name' => 'NIUE',
                'iso' => 'NU',
                'phonecode' => 683,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            157 => 
            array (
                'id' => 158,
                'name' => 'NORFOLK ISLAND',
                'iso' => 'NF',
                'phonecode' => 672,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            158 => 
            array (
                'id' => 159,
                'name' => 'NORTHERN MARIANA ISLANDS',
                'iso' => 'MP',
                'phonecode' => 1670,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            159 => 
            array (
                'id' => 160,
                'name' => 'NORWAY',
                'iso' => 'NO',
                'phonecode' => 47,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            160 => 
            array (
                'id' => 161,
                'name' => 'OMAN',
                'iso' => 'OM',
                'phonecode' => 968,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            161 => 
            array (
                'id' => 162,
                'name' => 'PAKISTAN',
                'iso' => 'PK',
                'phonecode' => 92,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            162 => 
            array (
                'id' => 163,
                'name' => 'PALAU',
                'iso' => 'PW',
                'phonecode' => 680,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            163 => 
            array (
                'id' => 164,
                'name' => 'PALESTINIAN TERRITORY, OCCUPIED',
                'iso' => 'PS',
                'phonecode' => 970,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            164 => 
            array (
                'id' => 165,
                'name' => 'PANAMA',
                'iso' => 'PA',
                'phonecode' => 507,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            165 => 
            array (
                'id' => 166,
                'name' => 'PAPUA NEW GUINEA',
                'iso' => 'PG',
                'phonecode' => 675,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            166 => 
            array (
                'id' => 167,
                'name' => 'PARAGUAY',
                'iso' => 'PY',
                'phonecode' => 595,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            167 => 
            array (
                'id' => 168,
                'name' => 'PERU',
                'iso' => 'PE',
                'phonecode' => 51,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            168 => 
            array (
                'id' => 169,
                'name' => 'PHILIPPINES',
                'iso' => 'PH',
                'phonecode' => 63,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            169 => 
            array (
                'id' => 170,
                'name' => 'PITCAIRN',
                'iso' => 'PN',
                'phonecode' => 0,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            170 => 
            array (
                'id' => 171,
                'name' => 'POLAND',
                'iso' => 'PL',
                'phonecode' => 48,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            171 => 
            array (
                'id' => 172,
                'name' => 'PORTUGAL',
                'iso' => 'PT',
                'phonecode' => 351,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            172 => 
            array (
                'id' => 173,
                'name' => 'PUERTO RICO',
                'iso' => 'PR',
                'phonecode' => 1787,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            173 => 
            array (
                'id' => 174,
                'name' => 'QATAR',
                'iso' => 'QA',
                'phonecode' => 974,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            174 => 
            array (
                'id' => 175,
                'name' => 'REUNION',
                'iso' => 'RE',
                'phonecode' => 262,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            175 => 
            array (
                'id' => 176,
                'name' => 'ROMANIA',
                'iso' => 'RO',
                'phonecode' => 40,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            176 => 
            array (
                'id' => 177,
                'name' => 'RUSSIAN FEDERATION',
                'iso' => 'RU',
                'phonecode' => 70,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            177 => 
            array (
                'id' => 178,
                'name' => 'RWANDA',
                'iso' => 'RW',
                'phonecode' => 250,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            178 => 
            array (
                'id' => 179,
                'name' => 'SAINT HELENA',
                'iso' => 'SH',
                'phonecode' => 290,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            179 => 
            array (
                'id' => 180,
                'name' => 'SAINT KITTS AND NEVIS',
                'iso' => 'KN',
                'phonecode' => 1869,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            180 => 
            array (
                'id' => 181,
                'name' => 'SAINT LUCIA',
                'iso' => 'LC',
                'phonecode' => 1758,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            181 => 
            array (
                'id' => 182,
                'name' => 'SAINT PIERRE AND MIQUELON',
                'iso' => 'PM',
                'phonecode' => 508,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            182 => 
            array (
                'id' => 183,
                'name' => 'SAINT VINCENT AND THE GRENADINES',
                'iso' => 'VC',
                'phonecode' => 1784,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            183 => 
            array (
                'id' => 184,
                'name' => 'SAMOA',
                'iso' => 'WS',
                'phonecode' => 684,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            184 => 
            array (
                'id' => 185,
                'name' => 'SAN MARINO',
                'iso' => 'SM',
                'phonecode' => 378,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            185 => 
            array (
                'id' => 186,
                'name' => 'SAO TOME AND PRINCIPE',
                'iso' => 'ST',
                'phonecode' => 239,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            186 => 
            array (
                'id' => 187,
                'name' => 'SAUDI ARABIA',
                'iso' => 'SA',
                'phonecode' => 966,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            187 => 
            array (
                'id' => 188,
                'name' => 'SENEGAL',
                'iso' => 'SN',
                'phonecode' => 221,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            188 => 
            array (
                'id' => 189,
                'name' => 'SERBIA AND MONTENEGRO',
                'iso' => 'CS',
                'phonecode' => 381,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            189 => 
            array (
                'id' => 190,
                'name' => 'SEYCHELLES',
                'iso' => 'SC',
                'phonecode' => 248,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            190 => 
            array (
                'id' => 191,
                'name' => 'SIERRA LEONE',
                'iso' => 'SL',
                'phonecode' => 232,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            191 => 
            array (
                'id' => 192,
                'name' => 'SINGAPORE',
                'iso' => 'SG',
                'phonecode' => 65,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            192 => 
            array (
                'id' => 193,
                'name' => 'SLOVAKIA',
                'iso' => 'SK',
                'phonecode' => 421,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            193 => 
            array (
                'id' => 194,
                'name' => 'SLOVENIA',
                'iso' => 'SI',
                'phonecode' => 386,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            194 => 
            array (
                'id' => 195,
                'name' => 'SOLOMON ISLANDS',
                'iso' => 'SB',
                'phonecode' => 677,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            195 => 
            array (
                'id' => 196,
                'name' => 'SOMALIA',
                'iso' => 'SO',
                'phonecode' => 252,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            196 => 
            array (
                'id' => 197,
                'name' => 'SOUTH AFRICA',
                'iso' => 'ZA',
                'phonecode' => 27,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            197 => 
            array (
                'id' => 198,
                'name' => 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS',
                'iso' => 'GS',
                'phonecode' => 0,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            198 => 
            array (
                'id' => 199,
                'name' => 'SPAIN',
                'iso' => 'ES',
                'phonecode' => 34,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            199 => 
            array (
                'id' => 200,
                'name' => 'SRI LANKA',
                'iso' => 'LK',
                'phonecode' => 94,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            200 => 
            array (
                'id' => 201,
                'name' => 'SUDAN',
                'iso' => 'SD',
                'phonecode' => 249,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            201 => 
            array (
                'id' => 202,
                'name' => 'SURINAME',
                'iso' => 'SR',
                'phonecode' => 597,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            202 => 
            array (
                'id' => 203,
                'name' => 'SVALBARD AND JAN MAYEN',
                'iso' => 'SJ',
                'phonecode' => 47,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            203 => 
            array (
                'id' => 204,
                'name' => 'SWAZILAND',
                'iso' => 'SZ',
                'phonecode' => 268,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            204 => 
            array (
                'id' => 205,
                'name' => 'SWEDEN',
                'iso' => 'SE',
                'phonecode' => 46,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            205 => 
            array (
                'id' => 206,
                'name' => 'SWITZERLAND',
                'iso' => 'CH',
                'phonecode' => 41,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            206 => 
            array (
                'id' => 207,
                'name' => 'SYRIAN ARAB REPUBLIC',
                'iso' => 'SY',
                'phonecode' => 963,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            207 => 
            array (
                'id' => 208,
                'name' => 'TAIWAN, PROVINCE OF CHINA',
                'iso' => 'TW',
                'phonecode' => 886,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            208 => 
            array (
                'id' => 209,
                'name' => 'TAJIKISTAN',
                'iso' => 'TJ',
                'phonecode' => 992,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            209 => 
            array (
                'id' => 210,
                'name' => 'TANZANIA, UNITED REPUBLIC OF',
                'iso' => 'TZ',
                'phonecode' => 255,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            210 => 
            array (
                'id' => 211,
                'name' => 'THAILAND',
                'iso' => 'TH',
                'phonecode' => 66,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            211 => 
            array (
                'id' => 212,
                'name' => 'TIMOR-LESTE',
                'iso' => 'TL',
                'phonecode' => 670,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            212 => 
            array (
                'id' => 213,
                'name' => 'TOGO',
                'iso' => 'TG',
                'phonecode' => 228,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            213 => 
            array (
                'id' => 214,
                'name' => 'TOKELAU',
                'iso' => 'TK',
                'phonecode' => 690,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            214 => 
            array (
                'id' => 215,
                'name' => 'TONGA',
                'iso' => 'TO',
                'phonecode' => 676,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            215 => 
            array (
                'id' => 216,
                'name' => 'TRINIDAD AND TOBAGO',
                'iso' => 'TT',
                'phonecode' => 1868,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            216 => 
            array (
                'id' => 217,
                'name' => 'TUNISIA',
                'iso' => 'TN',
                'phonecode' => 216,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            217 => 
            array (
                'id' => 218,
                'name' => 'TURKEY',
                'iso' => 'TR',
                'phonecode' => 90,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            218 => 
            array (
                'id' => 219,
                'name' => 'TURKMENISTAN',
                'iso' => 'TM',
                'phonecode' => 7370,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            219 => 
            array (
                'id' => 220,
                'name' => 'TURKS AND CAICOS ISLANDS',
                'iso' => 'TC',
                'phonecode' => 1649,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            220 => 
            array (
                'id' => 221,
                'name' => 'TUVALU',
                'iso' => 'TV',
                'phonecode' => 688,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            221 => 
            array (
                'id' => 222,
                'name' => 'UGANDA',
                'iso' => 'UG',
                'phonecode' => 256,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            222 => 
            array (
                'id' => 223,
                'name' => 'UKRAINE',
                'iso' => 'UA',
                'phonecode' => 380,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            223 => 
            array (
                'id' => 224,
                'name' => 'UNITED ARAB EMIRATES',
                'iso' => 'AE',
                'phonecode' => 971,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            224 => 
            array (
                'id' => 225,
                'name' => 'UNITED KINGDOM',
                'iso' => 'GB',
                'phonecode' => 44,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            225 => 
            array (
                'id' => 226,
                'name' => 'UNITED STATES',
                'iso' => 'US',
                'phonecode' => 1,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            226 => 
            array (
                'id' => 227,
                'name' => 'UNITED STATES MINOR OUTLYING ISLANDS',
                'iso' => 'UM',
                'phonecode' => 1,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            227 => 
            array (
                'id' => 228,
                'name' => 'URUGUAY',
                'iso' => 'UY',
                'phonecode' => 598,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            228 => 
            array (
                'id' => 229,
                'name' => 'UZBEKISTAN',
                'iso' => 'UZ',
                'phonecode' => 998,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            229 => 
            array (
                'id' => 230,
                'name' => 'VANUATU',
                'iso' => 'VU',
                'phonecode' => 678,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            230 => 
            array (
                'id' => 231,
                'name' => 'VENEZUELA',
                'iso' => 'VE',
                'phonecode' => 58,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            231 => 
            array (
                'id' => 232,
                'name' => 'VIET NAM',
                'iso' => 'VN',
                'phonecode' => 84,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            232 => 
            array (
                'id' => 233,
                'name' => 'VIRGIN ISLANDS, BRITISH',
                'iso' => 'VG',
                'phonecode' => 1284,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            233 => 
            array (
                'id' => 234,
                'name' => 'VIRGIN ISLANDS, U.S.',
                'iso' => 'VI',
                'phonecode' => 1340,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            234 => 
            array (
                'id' => 235,
                'name' => 'WALLIS AND FUTUNA',
                'iso' => 'WF',
                'phonecode' => 681,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            235 => 
            array (
                'id' => 236,
                'name' => 'WESTERN SAHARA',
                'iso' => 'EH',
                'phonecode' => 212,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            236 => 
            array (
                'id' => 237,
                'name' => 'YEMEN',
                'iso' => 'YE',
                'phonecode' => 967,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            237 => 
            array (
                'id' => 238,
                'name' => 'ZAMBIA',
                'iso' => 'ZM',
                'phonecode' => 260,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
            238 => 
            array (
                'id' => 239,
                'name' => 'ZIMBABWE',
                'iso' => 'ZW',
                'phonecode' => 263,
                'status' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-08-01 11:14:31',
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}