<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TblHomeTypesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('tbl_home_types')->delete();
        
        \DB::table('tbl_home_types')->insert(array (
            0 => 
            array (
                'id' => 1,
                'ru_property_type_id' => 3,
                'ru_ota_code' => 3,
                'name' => 'Apartments',
                'status' => 1,
                'deleted_at' => NULL,
                'position' => 0,
                'add_ip' => NULL,
                'add_by' => NULL,
                'update_ip' => NULL,
                'update_by' => NULL,
                'url_key' => NULL,
                'meta_title' => NULL,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2025-05-05 08:38:34',
            ),
            1 => 
            array (
                'id' => 2,
                'ru_property_type_id' => 4,
                'ru_ota_code' => 4,
                'name' => 'Bed and Breakfast',
                'status' => 1,
                'deleted_at' => NULL,
                'position' => 0,
                'add_ip' => '49.205.177.161',
                'add_by' => 'Super',
                'update_ip' => NULL,
                'update_by' => NULL,
                'url_key' => 'bed-and-breakfast',
                'meta_title' => 'Bed and Breakfast',
                'meta_keyword' => 'Bed and Breakfast',
                'meta_description' => 'Bed and Breakfast',
                'created_at' => NULL,
                'updated_at' => '2025-05-07 16:17:13',
            ),
            2 => 
            array (
                'id' => 3,
                'ru_property_type_id' => 7,
                'ru_ota_code' => 7,
                'name' => 'Chalet',
                'status' => 1,
                'deleted_at' => '2024-11-11 11:49:34',
                'position' => 0,
                'add_ip' => NULL,
                'add_by' => NULL,
                'update_ip' => NULL,
                'update_by' => NULL,
                'url_key' => NULL,
                'meta_title' => NULL,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'id' => 5,
                'ru_property_type_id' => 20,
                'ru_ota_code' => 20,
                'name' => 'Hotel',
                'status' => 1,
                'deleted_at' => '2024-11-11 11:49:34',
                'position' => 0,
                'add_ip' => NULL,
                'add_by' => NULL,
                'update_ip' => NULL,
                'update_by' => NULL,
                'url_key' => NULL,
                'meta_title' => NULL,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'id' => 6,
                'ru_property_type_id' => 22,
                'ru_ota_code' => 22,
                'name' => 'Lodge',
                'status' => 1,
                'deleted_at' => '2024-11-11 11:49:34',
                'position' => 0,
                'add_ip' => NULL,
                'add_by' => NULL,
                'update_ip' => NULL,
                'update_by' => NULL,
                'url_key' => NULL,
                'meta_title' => NULL,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'id' => 7,
                'ru_property_type_id' => 30,
                'ru_ota_code' => 30,
                'name' => 'Resort',
                'status' => 1,
                'deleted_at' => NULL,
                'position' => 0,
                'add_ip' => NULL,
                'add_by' => NULL,
                'update_ip' => NULL,
                'update_by' => NULL,
                'url_key' => NULL,
                'meta_title' => NULL,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'id' => 8,
                'ru_property_type_id' => 35,
                'ru_ota_code' => 35,
                'name' => 'Villas',
                'status' => 1,
                'deleted_at' => NULL,
                'position' => 0,
                'add_ip' => '49.205.177.161',
                'add_by' => 'Super',
                'update_ip' => NULL,
                'update_by' => NULL,
                'url_key' => 'villas',
                'meta_title' => 'Villas',
                'meta_keyword' => 'Villas',
                'meta_description' => 'Villas',
                'created_at' => NULL,
                'updated_at' => '2025-05-07 16:17:03',
            ),
            7 => 
            array (
                'id' => 9,
                'ru_property_type_id' => 37,
                'ru_ota_code' => 37,
                'name' => 'Castle',
                'status' => 1,
                'deleted_at' => NULL,
                'position' => 0,
                'add_ip' => '49.205.177.161',
                'add_by' => 'Super',
                'update_ip' => NULL,
                'update_by' => NULL,
                'url_key' => 'castle',
                'meta_title' => 'Castle',
                'meta_keyword' => 'Castle',
                'meta_description' => 'Castle',
                'created_at' => NULL,
                'updated_at' => '2025-05-07 16:18:53',
            ),
            8 => 
            array (
                'id' => 10,
                'ru_property_type_id' => 63,
                'ru_ota_code' => 3,
                'name' => 'Aparthotel',
                'status' => 1,
                'deleted_at' => '2024-11-11 11:49:34',
                'position' => 0,
                'add_ip' => NULL,
                'add_by' => NULL,
                'update_ip' => NULL,
                'update_by' => NULL,
                'url_key' => NULL,
                'meta_title' => NULL,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'id' => 11,
                'ru_property_type_id' => 64,
                'ru_ota_code' => 31,
                'name' => 'Boat',
                'status' => 1,
                'deleted_at' => '2024-11-11 11:49:34',
                'position' => 0,
                'add_ip' => NULL,
                'add_by' => NULL,
                'update_ip' => NULL,
                'update_by' => NULL,
                'url_key' => NULL,
                'meta_title' => NULL,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'id' => 12,
                'ru_property_type_id' => 65,
                'ru_ota_code' => 5,
                'name' => 'Cottage',
                'status' => 1,
                'deleted_at' => '2024-11-11 11:49:34',
                'position' => 0,
                'add_ip' => NULL,
                'add_by' => NULL,
                'update_ip' => NULL,
                'update_by' => NULL,
                'url_key' => NULL,
                'meta_title' => NULL,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'id' => 13,
                'ru_property_type_id' => 66,
                'ru_ota_code' => 25,
                'name' => 'Camping',
                'status' => 1,
                'deleted_at' => '2024-11-11 11:49:34',
                'position' => 0,
                'add_ip' => NULL,
                'add_by' => NULL,
                'update_ip' => NULL,
                'update_by' => NULL,
                'url_key' => NULL,
                'meta_title' => NULL,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'id' => 14,
                'ru_property_type_id' => 67,
                'ru_ota_code' => 34,
                'name' => 'House',
                'status' => 1,
                'deleted_at' => '2024-11-11 11:49:34',
                'position' => 0,
                'add_ip' => NULL,
                'add_by' => NULL,
                'update_ip' => NULL,
                'update_by' => NULL,
                'url_key' => NULL,
                'meta_title' => NULL,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'id' => 15,
                'ru_property_type_id' => 68,
                'ru_ota_code' => 68,
                'name' => 'Private room in apartment',
                'status' => 1,
                'deleted_at' => '2024-11-11 11:49:34',
                'position' => 0,
                'add_ip' => NULL,
                'add_by' => NULL,
                'update_ip' => NULL,
                'update_by' => NULL,
                'url_key' => NULL,
                'meta_title' => NULL,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'id' => 16,
                'ru_property_type_id' => 69,
                'ru_ota_code' => 69,
                'name' => 'Shared room',
                'status' => 1,
                'deleted_at' => '2024-11-11 11:49:34',
                'position' => 0,
                'add_ip' => NULL,
                'add_by' => NULL,
                'update_ip' => NULL,
                'update_by' => NULL,
                'url_key' => NULL,
                'meta_title' => NULL,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'id' => 17,
                'ru_property_type_id' => NULL,
                'ru_ota_code' => NULL,
                'name' => 'Guest House',
                'status' => 1,
                'deleted_at' => NULL,
                'position' => 0,
                'add_ip' => '49.205.177.161',
                'add_by' => 'Super',
                'update_ip' => NULL,
                'update_by' => NULL,
                'url_key' => 'guest-house',
                'meta_title' => 'GREENVILLA PROPERTIES',
                'meta_keyword' => 'GUEST HOUSE',
                'meta_description' => 'GUEST HOUSE',
                'created_at' => '2024-12-02 12:04:02',
                'updated_at' => '2025-05-07 16:19:26',
            ),
            16 => 
            array (
                'id' => 18,
                'ru_property_type_id' => NULL,
                'ru_ota_code' => NULL,
                'name' => 'testing',
                'status' => 0,
                'deleted_at' => '2024-12-03 12:42:47',
                'position' => 0,
                'add_ip' => '49.205.177.161',
                'add_by' => 'test User',
                'update_ip' => '49.205.177.161',
                'update_by' => 'test User',
                'url_key' => 'testing',
                'meta_title' => 'test',
                'meta_keyword' => 'testing',
                'meta_description' => 'test',
                'created_at' => '2024-12-03 12:42:34',
                'updated_at' => '2024-12-03 12:42:47',
            ),
            17 => 
            array (
                'id' => 19,
                'ru_property_type_id' => 3,
                'ru_ota_code' => 3,
                'name' => 'Home stay',
                'status' => 1,
                'deleted_at' => NULL,
                'position' => 0,
                'add_ip' => '49.205.177.161',
                'add_by' => 'admin',
                'update_ip' => NULL,
                'update_by' => NULL,
                'url_key' => 'home-stay',
                'meta_title' => 'Home stay',
                'meta_keyword' => 'Home stay',
                'meta_description' => 'Home stay',
                'created_at' => '2025-01-13 11:07:15',
                'updated_at' => '2025-04-05 12:18:34',
            ),
            18 => 
            array (
                'id' => 20,
                'ru_property_type_id' => NULL,
                'ru_ota_code' => NULL,
                'name' => 'Taniya chauhan',
                'status' => 1,
                'deleted_at' => '2025-01-18 17:30:25',
                'position' => 0,
                'add_ip' => '49.205.177.161',
                'add_by' => 'admin',
                'update_ip' => '49.205.177.161',
                'update_by' => 'admin',
                'url_key' => 'taniya-chauhan',
                'meta_title' => 'Taniya chauhan',
                'meta_keyword' => 'Taniya chauhan',
                'meta_description' => 'Taniya chauhan',
                'created_at' => '2025-01-18 17:30:06',
                'updated_at' => '2025-01-18 17:30:25',
            ),
            19 => 
            array (
                'id' => 21,
                'ru_property_type_id' => NULL,
                'ru_ota_code' => NULL,
                'name' => 'vrf',
                'status' => 1,
                'deleted_at' => '2025-05-03 10:43:38',
                'position' => 0,
                'add_ip' => '49.205.177.161',
                'add_by' => 'Super',
                'update_ip' => NULL,
                'update_by' => NULL,
                'url_key' => 'vrf',
                'meta_title' => 'V are Family',
                'meta_keyword' => 'V are Family',
                'meta_description' => 'V are Family',
                'created_at' => '2025-05-03 10:43:02',
                'updated_at' => '2025-05-03 10:43:38',
            ),
        ));
        
        
    }
}